### ISSUE TITLE
canvas.restore() make errors in android M

### ISSUE THREAD

**Issue by tunye** [traex/RippleEffect#86]

**Comment by suyashdixit** [comment]
Please please somebody solve this!

**Comment by EliasMazz** [comment]
PLEASE +1

**Comment by Hive-Networks** [comment]
same problem +1

**Comment by mobeela** [comment]
+1

**Comment by fncapps** [comment]
+1

**Comment by a9595** [comment]
+1

**Comment by traex** [comment]
Please see #92. It will be released asap

**Comment by GirishBhalerao** [comment]
There are two solutions for this Problem. 
1) As I mentioned before - "Just downgrade your - targetSdkVersion to 22
It works for all versions" - This works fine if you have not launched your app with targetSdkVersion 23 yet. 
2) If you already have launched your app with targetSdkVersion 23 then, 
instead of adding  compile 'com.github.traex.rippleeffect:library:1.3' in dependancies, 
Download the project by clicking on link - https://codeload.github.com/traex/RippleEffect/zip/master
Get library from that and use that in your app. It works great...!!! :)

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/
